project:
  type: website

website:
  title: "Data Tales"
  favicon: statics/favicon.png
  site-url: https://blog-talesgomes.netlify.app
  repo-url: https://github.com/talesgomes27/quarto-blog
  open-graph: true
  twitter-card:
    creator: "@talesgomes27"
    card-style: summary_large_image
  page-footer:
    left: "Blog made with 🤎 and [Quarto](https://quarto.org/), by Tales Gomes."
    right:
      - icon: github
        href: https://github.com/talesgomes27/
      - icon: linkedin
        href: https://www.linkedin.com/in/talesgomes27/
      - icon: envelope
        href: mailto:talesgomes27@gmail.com
  navbar:
    right:
      - about.qmd
      - text: Resume
        href: https://talesgomes27.github.io/curriculo/resume.html
      - icon: github
        href: https://github.com/talesgomes27/
      - icon: twitter
        href: https://twitter.com/talesgomes27/
      - icon: linkedin
        href: https://www.linkedin.com/in/talesgomes27/
format:
  html:
    smooth-scroll: true
    theme:
      light: 
        - flatly
        - custom.scss 
      dark: 
        - darkly
        - custom.scss
    css: styles.css
    citations-hover: true
    footnotes-hover: true



