project:
  type: website


website:
  title: "Yet Another Data Blog"
  description: "A blog about data science, learning and technology by Tales Gomes"  
  image: social.jpg
  twitter-card: 
    title: "Yet Another Data Blog"
    description: "A blog about data science, learning and technology by Tales Gomes"
    card-style: summary_large_image
    image: "https://blog-talesgomes.netlify.app/social.jpg"
    creator: "@talesgomes27"
  open-graph: 
    title: "Yet Another Data Blog"
    description: "A blog about data science, learning and technology by Tales Gomes"
    image: "https://blog-talesgomes.netlify.app/social.jpg"
    site-name: "Yet Another Data Blog"
  favicon: favicon.png
  site-url: https://blog-talesgomes.netlify.app
  repo-url: https://github.com/talesgomes27/quarto-blog
  page-footer:
    left: "Blog made with 🤎 and [Quarto](https://quarto.org/), by Tales Gomes."
    right:
      - icon: github
        href: https://github.com/talesgomes27/
      - icon: linkedin
        href: https://www.linkedin.com/in/talesgomes27/
      - icon: envelope
        href: mailto:talesgomes27@gmail.com
  navbar:
    right:
      - text: Tales Gomes
        href: about.qmd
      - text: Resume
        href: https://talesgomes27.github.io/curriculo/resume.html
      - icon: github
        href: https://github.com/talesgomes27/
      - icon: twitter
        href: https://twitter.com/talesgomes27/
      - icon: linkedin
        href: https://www.linkedin.com/in/talesgomes27/
format:
  html:
    smooth-scroll: true
    theme:
      light: 
        - flatly
        - custom.scss 
      dark: 
        - darkly
        - custom.scss
    css: styles.css
    citations-hover: true
    footnotes-hover: true


editor: visual

comments:
  giscus:
    repo: talesgomes27/quarto-blog


